site_name: xtb_ase
site_author: Andrew S. Rosen
site_description: >-
  A fully featured ASE calculator for xTB
nav:
  - Home: index.md
  - Installation:
      - install_guide/install.md
  - User Guide:
      - user_guide/basics.md
      - user_guide/parameters.md
  - Developer Guide:
      - dev_guide/contributing.md
  - Code Documentation: reference/ # keep me!
  - About:
      - about/changelog.md
      - about/people.md
      - about/conduct.md
      - about/license.md

repo_url: https://github.com/Quantum-Accelerators/xtb_ase/
edit_uri: blob/main/docs/

theme:
  features:
    - content.action.edit
    - content.code.copy
    - content.code.select
    - content.code.annotate
    - content.tabs.link
    - content.tooltips
    - navigation.footer
    - navigation.path
    - navigation.tracking
    - navigation.sections
    - navigation.top
    - search.highlight
    - search.suggest
    - search.share
    - header.autohide
    - toc.follow
  name: material
  palette:
    primary: orange
    scheme: slate

markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.snippets
  - pymdownx.smartsymbols
  - pymdownx.superfences:
      custom_fences:
        - class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format ""
          name: mermaid
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

plugins:
  - search:
      separator: '[\s\-,:!=\[\]()"`/]+|\.(?!\d)|&[lg]t;|(?!\b)(?=[A-Z][a-z])'
  - autorefs
  - social
  - offline
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          import:
            - https://docs.python.org/3/objects.inv
            - https://numpy.org/doc/stable/objects.inv
            - https://cclib.github.io/objects.inv
            - https://wiki.fysik.dtu.dk/ase/objects.inv
            - https://jinja.palletsprojects.com/en/latest/objects.inv
          options:
            docstring_style: numpy
            docstring_section_style: list
            separate_signature: true
            merge_init_into_class: true
            docstring_options:
              ignore_init_summary: true
  - gen-files:
      scripts:
        - docs/gen_ref_pages.py
  - literate-nav:
      nav_file: SUMMARY.md
